### ISSUE TITLE
`packages` strips nested dependencies and workspaces

### ISSUE THREAD

**Issue by milesj** [robertohuertasm/package-lock-json-parser#3]
Hey @robertohuertasm 

Attempting to migrate to this lib instead of rolling my own, but ran into an issue. I'm not sure if this is by design or not.

So for `dependencies` and v1/2, this works great. But for `packages` and new v3, it looks like it doesn't parse correctly. In npm, most dep names are in the format of `node_modules/<dep>`, which this lib handles. But nested deps are in the format of `node_modules/<parent>/node_modules/<child>`, and these are completely lost (or overwritten by the non-nested one).

Furthermore, there are `workspaces/<name>` packages that are completely removed. These are useful in knowing what's in the npm workspace.

As an example, I'm attempting to parse this trimmed down file:

```json
{
    "name": "moon-examples",
    "version": "1.2.3",
    "lockfileVersion": 3,
    "requires": true,
    "packages": {
        "node_modules/tap/node_modules/yaml": {
            "version": "1.10.2",
            "dev": true,
            "inBundle": true,
            "license": "ISC",
            "engines": {
                "node": ">= 6"
            }
        },
        "node_modules/yaml": {
            "version": "2.2.2",
            "resolved": "https://registry.npmjs.org/yaml/-/yaml-2.2.2.tgz",
            "integrity": "sha512-CBKFWExMn46Foo4cldiChEzn7S7SRV+wqiluAb6xmueD/fGyRHIhX8m14vVGgeFWjN540nKCNVj6P21eQjgTuA==",
            "dev": true,
            "engines": {
                "node": ">= 14"
            }
        },
        "workspaces/libnpmdiff": {
            "version": "5.0.17",
            "license": "ISC",
            "dependencies": {
                "@npmcli/arborist": "^6.2.9",
                "@npmcli/disparity-colors": "^3.0.0",
                "@npmcli/installed-package-contents": "^2.0.2",
                "binary-extensions": "^2.2.0",
                "diff": "^5.1.0",
                "minimatch": "^9.0.0",
                "npm-package-arg": "^10.1.0",
                "pacote": "^15.0.8",
                "tar": "^6.1.13"
            },
            "devDependencies": {
                "@npmcli/eslint-config": "^4.0.0",
                "@npmcli/template-oss": "4.14.1",
                "tap": "^16.3.4"
            },
            "engines": {
                "node": "^14.17.0 || ^16.13.0 || >=18.0.0"
            }
        }
    }
}
```

But only `node_modules/yaml` (as `yaml` when parsed) is only returned. It may be best to just leave the names as-is?

**Comment by milesj** [comment]
Here's my PR testing the impl: https://github.com/moonrepo/moon/pull/831

**Comment by robertohuertasm** [comment]
Hey @milesj thanks for reporting this! I'll take a look.

**Comment by robertohuertasm** [comment]
Hi @milesj, nested dependencies are not taken into account for the moment. For what I've seen the dependency that it's effectively used is expressed as a normal dependency. 

Regarding workspace dependencies they seem to work. There's a new v0.3.0 version published.
