### ISSUE TITLE
Error "missing field `version`"

### ISSUE THREAD

**Issue by milesj** [robertohuertasm/package-lock-json-parser#7]
Hey @robertohuertasm  👋 

Me again, thanks for the work so far. I'm trying the 0.3.0 version and hit another snag. Looks like `version` isn't required in all cases. I believe this is the case I hit:

```
{
  "name": "test-node-npm-project",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "test-node-npm-project",
      "devDependencies": {
        "prettier": "2.7.0"
      }
    },
    "node_modules/prettier": {
      "version": "2.7.0",
      "resolved": "https://registry.npmjs.org/prettier/-/prettier-2.7.0.tgz",
      "integrity": "sha512-nwoX4GMFgxoPC6diHvSwmK/4yU8FFH3V8XWtLQrbj4IBsK2pkYhG4kf/ljF/haaZ/aii+wNJqISrCDPgxGWDVQ==",
      "dev": true,
      "bin": {
        "prettier": "bin-prettier.js"
      },
      "engines": {
        "node": ">=10.13.0"
      },
      "funding": {
        "url": "https://github.com/prettier/prettier?sponsor=1"
      }
    }
  },
  "dependencies": {
    "prettier": {
      "version": "2.7.0",
      "resolved": "https://registry.npmjs.org/prettier/-/prettier-2.7.0.tgz",
      "integrity": "sha512-nwoX4GMFgxoPC6diHvSwmK/4yU8FFH3V8XWtLQrbj4IBsK2pkYhG4kf/ljF/haaZ/aii+wNJqISrCDPgxGWDVQ==",
      "dev": true
    }
  }
}

```

I believe this only happens when using npm `workspaces`, so the root `""` doesn't have any info.

**Comment by robertohuertasm** [comment]
The root `""` is always ignored by the library as it gives information about the main package which is also present in the list of dependencies.

Regarding the `version`, as you mention, it seems that the only moment where the `version` is not required is in the workspace libraries. But these libraries get declared twice:

- Once without the `node_modules` prefix and including version
- And a second time with the `node_modules` prefix and without version.

At the moment, we're ignoring this second occurrence.  We're leveraging the fact that the version is required to silently swallow the parsing error happening when trying to parse a dependency without version.

**Comment by robertohuertasm** [comment]
Last version, 0.4.0, should fix your issue. I realised you were referring to the version of the file itself.
